/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import controller.InscribirAMateriaController;
import javax.swing.ImageIcon;
import javax.swing.JTable;

/**
 *
 * @author eljos
 */
public class InscribirAMateria extends javax.swing.JFrame {

    /**
     * Creates new form InscribirAMateria
     */
    public InscribirAMateria() {
        initComponents();
        myInitComponent();
        centrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMaterias = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMaterias = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnVerificarCorrelativas = new javax.swing.JButton();
        btnVerificarPlan = new javax.swing.JButton();
        btnInscribir = new javax.swing.JButton();
        btnMostrarMateriasParaCursar = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inscribir a Materia");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMaterias.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        lblMaterias.setText("Materias de la Carrera:");
        lblMaterias.setToolTipText("");
        getContentPane().add(lblMaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jTableMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jScrollPane1.setViewportView(jTableMaterias);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 690, 320));

        btnBack.setText("VOVER<--");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 100, 30));

        btnVerificarCorrelativas.setText("Verificar Correlativas");
        btnVerificarCorrelativas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarCorrelativasActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerificarCorrelativas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 453, 160, 40));

        btnVerificarPlan.setText("Verificar Plan de Estudio");
        btnVerificarPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarPlanActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerificarPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 190, 40));

        btnInscribir.setText("Inscribir");
        btnInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscribirActionPerformed(evt);
            }
        });
        getContentPane().add(btnInscribir, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 450, 130, 40));

        btnMostrarMateriasParaCursar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnMostrarMateriasParaCursar.setText("Mostrar Materias en Condición de Cursar");
        btnMostrarMateriasParaCursar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarMateriasParaCursarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrarMateriasParaCursar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 310, 30));
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        InscribirAMateriaController.back();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnVerificarCorrelativasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarCorrelativasActionPerformed
        // TODO add your handling code here:
        InscribirAMateriaController.verificarCorrelativas();
    }//GEN-LAST:event_btnVerificarCorrelativasActionPerformed

    private void btnVerificarPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarPlanActionPerformed
        // TODO add your handling code here:
        InscribirAMateriaController.verificarPlanEstudio();
    }//GEN-LAST:event_btnVerificarPlanActionPerformed

    private void btnInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscribirActionPerformed
        // TODO add your handling code here:
        InscribirAMateriaController.inscribirAlumnoAMateria();
    }//GEN-LAST:event_btnInscribirActionPerformed

    private void btnMostrarMateriasParaCursarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarMateriasParaCursarActionPerformed
        // TODO add your handling code here:
        InscribirAMateriaController.mostrarMateriasParaCursar();
    }//GEN-LAST:event_btnMostrarMateriasParaCursarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InscribirAMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InscribirAMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InscribirAMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InscribirAMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InscribirAMateria().setVisible(true);
            }
        });
    }

    
    public void myInitComponent(){
        ImageIcon image = new ImageIcon("C:\\Users\\eljos\\Documents\\NetBeansProjects\\Facultad\\src\\main\\java\\imagenes\\carreras-universitarias-programas.png");
        Fondo.setIcon(image);
    }

    public void centrar(){
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }
    
    
    public JTable getjTableMaterias() {
        return jTableMaterias;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnInscribir;
    private javax.swing.JButton btnMostrarMateriasParaCursar;
    private javax.swing.JButton btnVerificarCorrelativas;
    private javax.swing.JButton btnVerificarPlan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMaterias;
    private javax.swing.JLabel lblMaterias;
    // End of variables declaration//GEN-END:variables
}
