/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import controller.MostrarCarrerasController;
import controller.NuevaCarreraController;
import javax.swing.*;
import javax.swing.table.TableColumnModel;
import model.DB;

/**
 *
 * @author eljos
 */
public class MostrarCarreras extends JFrame {

    /**
     * Creates new form MostrarCarreras
     */
    public MostrarCarreras() {
        initComponents();
        myInitComponent();
        centrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        propuestas = new javax.swing.JLabel();
        seleccioneCarrera = new javax.swing.JLabel();
        mostrarAlumnos = new javax.swing.JButton();
        mostrarMaterias = new javax.swing.JButton();
        darBaja = new javax.swing.JButton();
        renombrar = new javax.swing.JButton();
        agregarCarrera = new javax.swing.JButton();
        back = new javax.swing.JButton();
        JTableCarreras = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Carreras");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        propuestas.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        propuestas.setText("Carreras en el Sistema:");
        getContentPane().add(propuestas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        seleccioneCarrera.setText("Seleccione una carrera...");
        getContentPane().add(seleccioneCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        mostrarAlumnos.setText("Mostrar Alumnos");
        mostrarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarAlumnosActionPerformed(evt);
            }
        });
        getContentPane().add(mostrarAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, -1, -1));

        mostrarMaterias.setText("Mostrar Materias");
        mostrarMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarMateriasActionPerformed(evt);
            }
        });
        getContentPane().add(mostrarMaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 150, -1));

        darBaja.setText("Dar de Baja Carrera");
        darBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darBajaActionPerformed(evt);
            }
        });
        getContentPane().add(darBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, -1, 60));

        renombrar.setText("Renombrar");
        renombrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renombrarActionPerformed(evt);
            }
        });
        getContentPane().add(renombrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 130, 60));

        agregarCarrera.setText("Agregar Carrera");
        agregarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarCarreraActionPerformed(evt);
            }
        });
        getContentPane().add(agregarCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 130, 60));

        back.setBackground(new java.awt.Color(255, 0, 0));
        back.setText("Volver <--");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 100, 52));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setRowHeight(20);
        jTable1.setRowMargin(10);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        JTableCarreras.setViewportView(jTable1);

        getContentPane().add(JTableCarreras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 600, 370));
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        MostrarCarrerasController.back();
    }//GEN-LAST:event_backActionPerformed

    private void agregarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarCarreraActionPerformed
        // TODO add your handling code here:
        MostrarCarrerasController.ocultarVentana();
        NuevaCarreraController.crearVentana();
    }//GEN-LAST:event_agregarCarreraActionPerformed

    private void darBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darBajaActionPerformed
        // TODO add your handling code here:
        MostrarCarrerasController.eliminarCarrera();
    }//GEN-LAST:event_darBajaActionPerformed

    private void renombrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renombrarActionPerformed
        // TODO add your handling code here:
        MostrarCarrerasController.renombrarCarrera();
    }//GEN-LAST:event_renombrarActionPerformed

    private void mostrarMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarMateriasActionPerformed
        // TODO add your handling code here:
        MostrarCarrerasController.mostrarMaterias();
    }//GEN-LAST:event_mostrarMateriasActionPerformed

    private void mostrarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarAlumnosActionPerformed
        // TODO add your handling code here:
        MostrarCarrerasController.mostrarAlumnos();
    }//GEN-LAST:event_mostrarAlumnosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarCarreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarCarreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarCarreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarCarreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MostrarCarreras mostrarCarreras = new MostrarCarreras();
                mostrarCarreras.setLocationRelativeTo(null);
                mostrarCarreras.setVisible(true);
            }
        });
    }
    
    public void myInitComponent(){
        ImageIcon image = new ImageIcon("C:\\Users\\eljos\\Documents\\NetBeansProjects\\Facultad\\src\\main\\java\\imagenes\\carreras-universitarias-programas.png");
        Fondo.setIcon(image);
    }

    public void centrar(){
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }
    



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JScrollPane JTableCarreras;
    private javax.swing.JButton agregarCarrera;
    private javax.swing.JButton back;
    private javax.swing.JButton darBaja;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton mostrarAlumnos;
    private javax.swing.JButton mostrarMaterias;
    private javax.swing.JLabel propuestas;
    private javax.swing.JButton renombrar;
    private javax.swing.JLabel seleccioneCarrera;
    // End of variables declaration//GEN-END:variables
}
