/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import controller.MostrarAlumnosMateriaController;
import javax.swing.ImageIcon;
import javax.swing.JTable;

/**
 *
 * @author eljos
 */
public class MostrarAlumnosMateria extends javax.swing.JFrame {

    /**
     * Creates new form MostrarAlumnosMateria
     */
    public MostrarAlumnosMateria() {
        initComponents();
        myInitComponent();
        centrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAlumnosCursada = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAlumnosMateria = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnTomarExamenes = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alumnos Cursando");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAlumnosCursada.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAlumnosCursada.setText("Alumnos en la Cursada de la Materia Seleccionada: ");
        getContentPane().add(lblAlumnosCursada, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jTableAlumnosMateria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableAlumnosMateria);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 680, 370));

        btnBack.setText("VOLVER<--");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, -1, -1));

        btnTomarExamenes.setText("Tomar Examenes");
        btnTomarExamenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTomarExamenesActionPerformed(evt);
            }
        });
        getContentPane().add(btnTomarExamenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 160, 60));
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        MostrarAlumnosMateriaController.back();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnTomarExamenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTomarExamenesActionPerformed
        // TODO add your handling code here:
        MostrarAlumnosMateriaController.tomarExamenParcial();
        
    }//GEN-LAST:event_btnTomarExamenesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarAlumnosMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarAlumnosMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarAlumnosMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarAlumnosMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarAlumnosMateria().setVisible(true);
            }
        });
    }
    
    public void myInitComponent(){
        ImageIcon image = new ImageIcon("C:\\Users\\eljos\\Documents\\NetBeansProjects\\Facultad\\src\\main\\java\\imagenes\\carreras-universitarias-programas.png");
        Fondo.setIcon(image);
    }

    public void centrar(){
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    public JTable getjTableAlumnosMateria() {
        return jTableAlumnosMateria;
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnTomarExamenes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAlumnosMateria;
    private javax.swing.JLabel lblAlumnosCursada;
    // End of variables declaration//GEN-END:variables
}
