/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author eljos
 */
import controller.MostrarMateriasController;
import controller.NuevaMateriaController;
import javax.swing.*;

public class MostrarMaterias extends JFrame {

    /**
     * Creates new form MostrarMaterias
     */
    
    public MostrarMaterias() {
        initComponents();
        myInitComponent();
        centrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        definirCorrelativas = new javax.swing.JButton();
        mostrarAlumnos = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMaterias = new javax.swing.JTable();
        lblMaterias = new javax.swing.JLabel();
        btnAddMateria = new javax.swing.JButton();
        btnEliminarMateria = new javax.swing.JButton();
        btnMostrarCorrelativas = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Materias de la Carrera");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        definirCorrelativas.setText("Definir Correlativas");
        definirCorrelativas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                definirCorrelativasActionPerformed(evt);
            }
        });
        getContentPane().add(definirCorrelativas, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 448, -1, -1));

        mostrarAlumnos.setText("Mostrar Alumnos");
        mostrarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarAlumnosActionPerformed(evt);
            }
        });
        getContentPane().add(mostrarAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, -1, -1));

        back.setBackground(new java.awt.Color(255, 0, 0));
        back.setText("Volver<--");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 90, 50));

        jTableMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jScrollPane1.setViewportView(jTableMaterias);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 700, 360));

        lblMaterias.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblMaterias.setText("Materias de la Carrera Seleccionada:");
        getContentPane().add(lblMaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        btnAddMateria.setText("Agregar Materia");
        btnAddMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMateriaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, -1, -1));

        btnEliminarMateria.setText("Eliminar Materia");
        btnEliminarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMateriaActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 480, -1, -1));

        btnMostrarCorrelativas.setText("Mostrar Correlativas");
        btnMostrarCorrelativas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarCorrelativasActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrarCorrelativas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, -1, -1));
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        MostrarMateriasController.back(this);
    }//GEN-LAST:event_backActionPerformed

    private void btnAddMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMateriaActionPerformed
        // TODO add your handling code here:
        NuevaMateriaController.crearVentana(MostrarMateriasController.idCarrera);
        MostrarMateriasController.cerrarVentana();
    }//GEN-LAST:event_btnAddMateriaActionPerformed

    private void btnEliminarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMateriaActionPerformed
        // TODO add your handling code here:
        MostrarMateriasController.eliminarMateria();
    }//GEN-LAST:event_btnEliminarMateriaActionPerformed

    private void definirCorrelativasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_definirCorrelativasActionPerformed
        // TODO add your handling code here:
        MostrarMateriasController.definirMateriasCorrelativas();
    }//GEN-LAST:event_definirCorrelativasActionPerformed

    private void btnMostrarCorrelativasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarCorrelativasActionPerformed
        // TODO add your handling code here:
        MostrarMateriasController.mostrarMateriasCorrelativas();
    }//GEN-LAST:event_btnMostrarCorrelativasActionPerformed

    private void mostrarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarAlumnosActionPerformed
        // TODO add your handling code here:
        MostrarMateriasController.mostrarAlumnosMateria();
    }//GEN-LAST:event_mostrarAlumnosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MostrarMaterias mostrarMaterias = new MostrarMaterias();
                mostrarMaterias.setLocationRelativeTo(null);
                mostrarMaterias.setVisible(true);
            }
        });
    }
    
    public void myInitComponent(){
        ImageIcon image = new ImageIcon("C:\\Users\\eljos\\Documents\\NetBeansProjects\\Facultad\\src\\main\\java\\imagenes\\carreras-universitarias-programas.png");
        Fondo.setIcon(image);
    }

    public void centrar(){
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    public JTable getjTableMaterias() {
        return jTableMaterias;
    }

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton back;
    private javax.swing.JButton btnAddMateria;
    private javax.swing.JButton btnEliminarMateria;
    private javax.swing.JButton btnMostrarCorrelativas;
    private javax.swing.JButton definirCorrelativas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMaterias;
    private javax.swing.JLabel lblMaterias;
    private javax.swing.JButton mostrarAlumnos;
    // End of variables declaration//GEN-END:variables
}
