/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import controller.MostrarAlumnosController;
import controller.NuevoAlumnoController;
import javax.swing.ImageIcon;
import javax.swing.JTable;

/**
 *
 * @author eljos
 */
public class MostrarAlumnos extends javax.swing.JFrame {

    /**
     * Creates new form MostrarAlumnos
     */
    public MostrarAlumnos() {
        initComponents();
        myInitComponent();
        centrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void myInitComponent(){
        ImageIcon image = new ImageIcon("C:\\Users\\eljos\\Documents\\NetBeansProjects\\Facultad\\src\\main\\java\\imagenes\\carreras-universitarias-programas.png");
        Fondo.setIcon(image);
    }

    public void centrar(){
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    public JTable getjTableAlumnos() {
        return jTableAlumnos;
    }

    public void setjTableAlumnos(JTable jTableAlumnos) {
        this.jTableAlumnos = jTableAlumnos;
    }
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAlumnos = new javax.swing.JTable();
        lblAlumnos = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnEliminarAlumno = new javax.swing.JButton();
        btnAgregarAlumno = new javax.swing.JButton();
        btnInscribirCarrera = new javax.swing.JButton();
        btnIncribirMateria = new javax.swing.JButton();
        btnInscribirExamen = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alumnos en el Sistema");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(jTableAlumnos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 520, 410));

        lblAlumnos.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblAlumnos.setText("Alumnos:");
        getContentPane().add(lblAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 170, -1));

        btnBack.setText("VOLVER<--");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, -1, -1));

        btnEliminarAlumno.setText("Eliminar Alumno");
        btnEliminarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAlumnoActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 450, 160, 40));

        btnAgregarAlumno.setText("Agregar Alumno");
        btnAgregarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAlumnoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, 160, 40));

        btnInscribirCarrera.setText("Inscribir a Carrera");
        btnInscribirCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscribirCarreraActionPerformed(evt);
            }
        });
        getContentPane().add(btnInscribirCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, -1, -1));

        btnIncribirMateria.setText("Inscribir a Materia");
        btnIncribirMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncribirMateriaActionPerformed(evt);
            }
        });
        getContentPane().add(btnIncribirMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, -1, -1));

        btnInscribirExamen.setText("Ver Historial Académico");
        btnInscribirExamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscribirExamenActionPerformed(evt);
            }
        });
        getContentPane().add(btnInscribirExamen, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 530, 180, -1));
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        MostrarAlumnosController.back();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAgregarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAlumnoActionPerformed
//        // TODO add your handling code here:
//        NuevoAlumnoController.mostrarVentana();
//        MostrarAlumnosController.ocultarVentana();
          MostrarAlumnosController.agregarAlumno();
    }//GEN-LAST:event_btnAgregarAlumnoActionPerformed

    private void btnInscribirCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscribirCarreraActionPerformed
        // TODO add your handling code here:
        MostrarAlumnosController.inscribirACarrera();
    }//GEN-LAST:event_btnInscribirCarreraActionPerformed

    private void btnEliminarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAlumnoActionPerformed
        // TODO add your handling code here:
        MostrarAlumnosController.eliminarAlumno();
    }//GEN-LAST:event_btnEliminarAlumnoActionPerformed

    private void btnIncribirMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncribirMateriaActionPerformed
        // TODO add your handling code here:
        MostrarAlumnosController.inscribirAMateria();
    }//GEN-LAST:event_btnIncribirMateriaActionPerformed

    private void btnInscribirExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscribirExamenActionPerformed
        // TODO add your handling code here:
        MostrarAlumnosController.verHistorialAcademico();
    }//GEN-LAST:event_btnInscribirExamenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarAlumnos().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnAgregarAlumno;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEliminarAlumno;
    private javax.swing.JButton btnIncribirMateria;
    private javax.swing.JButton btnInscribirCarrera;
    private javax.swing.JButton btnInscribirExamen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAlumnos;
    private javax.swing.JLabel lblAlumnos;
    // End of variables declaration//GEN-END:variables
}
