
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import controller.MostrarAlumnosController;
import controller.NuevoAlumnoController;
import javax.swing.*;

/**
 *
 * @author eljos
 */
public class NuevoAlumno extends JFrame {

    /**
     * Creates new form NuevoAlumno
     */
    public NuevoAlumno() {
        initComponents();
        myInitComponent();
        centrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        legajoAlumno = new javax.swing.JLabel();
        textLegajoAlumno = new javax.swing.JTextField();
        dniAlumno = new javax.swing.JLabel();
        textDniAlumno = new javax.swing.JTextField();
        nombreAlumno = new javax.swing.JLabel();
        textNombreAlumno = new javax.swing.JTextField();
        apellidoAlumno = new javax.swing.JLabel();
        textApellidoAlumno = new javax.swing.JTextField();
        domicilioAlumno = new javax.swing.JLabel();
        JTxtDomicilio = new javax.swing.JTextField();
        correoAlumno = new javax.swing.JLabel();
        textCorreoAlumno = new javax.swing.JTextField();
        cancelar = new javax.swing.JButton();
        crearAlumno = new javax.swing.JButton();
        legajoVerificado = new javax.swing.JLabel();
        dniVerificado = new javax.swing.JLabel();
        nombreVerificado = new javax.swing.JLabel();
        apellidoVerificado = new javax.swing.JLabel();
        localidadVerificada = new javax.swing.JLabel();
        calleVerificada = new javax.swing.JLabel();
        numeroVerificado = new javax.swing.JLabel();
        correoVerificado = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nuevo Alumno");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        legajoAlumno.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        legajoAlumno.setText("Legajo del Alumno ");
        getContentPane().add(legajoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 49, -1, -1));
        getContentPane().add(textLegajoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 78, 100, -1));

        dniAlumno.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        dniAlumno.setText("DNI del Alumno ");
        getContentPane().add(dniAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 49, -1, -1));
        getContentPane().add(textDniAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 78, 100, -1));

        nombreAlumno.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        nombreAlumno.setText("Nombre Del Alumno ");
        getContentPane().add(nombreAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 193, -1, -1));
        getContentPane().add(textNombreAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 222, 200, -1));

        apellidoAlumno.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        apellidoAlumno.setText("Apellido del Alumno");
        getContentPane().add(apellidoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 193, -1, -1));
        getContentPane().add(textApellidoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 222, 220, -1));

        domicilioAlumno.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        domicilioAlumno.setText("Domicilio del Alumno:");
        getContentPane().add(domicilioAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));
        getContentPane().add(JTxtDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 290, 20));

        correoAlumno.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        correoAlumno.setText("Correo del Alumno");
        getContentPane().add(correoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, -1, -1));
        getContentPane().add(textCorreoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 290, -1));

        cancelar.setBackground(new java.awt.Color(255, 0, 0));
        cancelar.setText("Cancelar <--");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 150, 50));

        crearAlumno.setBackground(new java.awt.Color(0, 204, 0));
        crearAlumno.setText("Crear Alumno");
        crearAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearAlumnoActionPerformed(evt);
            }
        });
        getContentPane().add(crearAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 150, 50));
        getContentPane().add(legajoVerificado, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 100, 100, 20));

        dniVerificado.setForeground(new java.awt.Color(0, 204, 0));
        getContentPane().add(dniVerificado, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 100, 100, 20));
        getContentPane().add(nombreVerificado, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 242, 190, 20));
        getContentPane().add(apellidoVerificado, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 242, 210, 20));
        getContentPane().add(localidadVerificada, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 380, 200, 20));
        getContentPane().add(calleVerificada, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 427, 200, 20));
        getContentPane().add(numeroVerificado, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 470, 50, 20));
        getContentPane().add(correoVerificado, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 390, 210, 20));
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        NuevoAlumnoController.back();
    }//GEN-LAST:event_cancelarActionPerformed

    private void crearAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearAlumnoActionPerformed
        // TODO add your handling code here:
        NuevoAlumnoController.crearAlumno();
    }//GEN-LAST:event_crearAlumnoActionPerformed

    
    
    /**
     line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NuevoAlumno nuevoAlumno = new NuevoAlumno();
                nuevoAlumno.setLocationRelativeTo(null);
                nuevoAlumno.setVisible(true);
            }
        });
    }
    
    public void myInitComponent(){
        ImageIcon image = new ImageIcon("C:\\Users\\eljos\\Documents\\NetBeansProjects\\Facultad\\src\\main\\java\\imagenes\\carreras-universitarias-programas.png");
        Fondo.setIcon(image);
    }

    public void centrar(){
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    public JTextField getTextApellidoAlumno() {
        return textApellidoAlumno;
    }

    public JTextField getTextCalle() {
        return JTxtDomicilio;
    }

    public JTextField getTextCorreoAlumno() {
        return textCorreoAlumno;
    }

    public JTextField getTextDniAlumno() {
        return textDniAlumno;
    }

    public JTextField getTextLegajoAlumno() {
        return textLegajoAlumno;
    }


    public JTextField getTextNombreAlumno() {
        return textNombreAlumno;
    }


    public void setApellidoVerificado(JLabel apellidoVerificado) {
        this.apellidoVerificado = apellidoVerificado;
    }

    public void setCalleVerificada(JLabel calleVerificada) {
        this.calleVerificada = calleVerificada;
    }

    public void setCorreoVerificado(JLabel correoVerificado) {
        this.correoVerificado = correoVerificado;
    }

    public void setDniVerificado(JLabel dniVerificado) {
        this.dniVerificado = dniVerificado;
    }

    public void setLegajoVerificado(JLabel legajoVerificado) {
        this.legajoVerificado = legajoVerificado;
    }

    public void setLocalidadVerificada(JLabel localidadVerificada) {
        this.localidadVerificada = localidadVerificada;
    }

    public void setNombreVerificado(JLabel nombreVerificado) {
        this.nombreVerificado = nombreVerificado;
    }

    public void setNumeroVerificado(JLabel numeroVerificado) {
        this.numeroVerificado = numeroVerificado;
    }

    public JLabel getDniVerificado() {
        return dniVerificado;
    }

    public JLabel getApellidoVerificado() {
        return apellidoVerificado;
    }

    public JLabel getCorreoVerificado() {
        return correoVerificado;
    }

    public JLabel getLegajoVerificado() {
        return legajoVerificado;
    }

    public JLabel getLocalidadVerificada() {
        return localidadVerificada;
    }

    public JLabel getNombreVerificado() {
        return nombreVerificado;
    }

    public JLabel getNumeroVerificado() {
        return numeroVerificado;
    }

    public JLabel getCalleVerificada() {
        return calleVerificada;
    }

    public JTextField getJTxtDomicilio() {
        return JTxtDomicilio;
    }

    public void setJTxtDomicilio(JTextField JTxtDomicilio) {
        this.JTxtDomicilio = JTxtDomicilio;
    }
    
    

    public void setTextApellidoAlumno(String textApellidoAlumno) {
        this.textApellidoAlumno.setText(textApellidoAlumno); 
    }

    public void setTextCalle(String textCalle) {
        this.JTxtDomicilio.setText(textCalle);
    }

    public void setTextCorreoAlumno(String textCorreoAlumno) {
        this.textCorreoAlumno.setText(textCorreoAlumno);
    }

    public void setTextDniAlumno(String textDniAlumno) {
        this.textDniAlumno.setText(textDniAlumno);
    }

    public void setTextLegajoAlumno(String textLegajoAlumno) {
        this.textLegajoAlumno.setText(textLegajoAlumno); 
    }

    public void setTextNombreAlumno(String textNombreAlumno) {
        this.textNombreAlumno.setText(textNombreAlumno); 
    }

    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JTextField JTxtDomicilio;
    private javax.swing.JLabel apellidoAlumno;
    private javax.swing.JLabel apellidoVerificado;
    private javax.swing.JLabel calleVerificada;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel correoAlumno;
    private javax.swing.JLabel correoVerificado;
    private javax.swing.JButton crearAlumno;
    private javax.swing.JLabel dniAlumno;
    private javax.swing.JLabel dniVerificado;
    private javax.swing.JLabel domicilioAlumno;
    private javax.swing.JLabel legajoAlumno;
    private javax.swing.JLabel legajoVerificado;
    private javax.swing.JLabel localidadVerificada;
    private javax.swing.JLabel nombreAlumno;
    private javax.swing.JLabel nombreVerificado;
    private javax.swing.JLabel numeroVerificado;
    private javax.swing.JTextField textApellidoAlumno;
    private javax.swing.JTextField textCorreoAlumno;
    private javax.swing.JTextField textDniAlumno;
    private javax.swing.JTextField textLegajoAlumno;
    private javax.swing.JTextField textNombreAlumno;
    // End of variables declaration//GEN-END:variables
}
