/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author eljos
 */

import controller.MostrarCarrerasController;
import controller.NuevaCarreraController;
import controller.PrincipalController;
import javax.swing.*;
public class NuevaCarrera extends javax.swing.JFrame {

    /**
     * Creates new form NuevaCarrera
     */
    public NuevaCarrera() {
        initComponents();
        myInitComponent();
        centrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreCarrera = new javax.swing.JLabel();
        textNombreCarrera = new javax.swing.JTextField();
        codigoCarrera = new javax.swing.JLabel();
        textCodigoCarrera = new javax.swing.JTextField();
        tipoPlan = new javax.swing.JLabel();
        listaTiposPlanes = new javax.swing.JComboBox<>();
        back = new javax.swing.JButton();
        crearCarrera = new javax.swing.JButton();
        lblGrado = new javax.swing.JLabel();
        grados = new javax.swing.JComboBox<>();
        lblDescripcionPlan = new javax.swing.JLabel();
        lblIngresePorcentaje = new javax.swing.JLabel();
        jTxtPorcentaje = new javax.swing.JTextField();
        lblIcono = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nueva Carrera");
        setMaximumSize(new java.awt.Dimension(799, 547));
        setMinimumSize(new java.awt.Dimension(799, 547));
        setName("NuevaCarrera"); // NOI18N
        setPreferredSize(new java.awt.Dimension(799, 547));
        setResizable(false);
        setSize(new java.awt.Dimension(799, 547));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreCarrera.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        nombreCarrera.setText("Nombre de la Nueva Carrera");
        getContentPane().add(nombreCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        textNombreCarrera.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(textNombreCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 570, -1));

        codigoCarrera.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        codigoCarrera.setText("Codigo de la Carrera");
        getContentPane().add(codigoCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));
        getContentPane().add(textCodigoCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 70, -1));

        tipoPlan.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        tipoPlan.setText("Asignar Plan de Estudio");
        getContentPane().add(tipoPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        listaTiposPlanes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E" }));
        getContentPane().add(listaTiposPlanes, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        back.setBackground(new java.awt.Color(255, 0, 0));
        back.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        back.setText("ATRÁS <--");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 120, 40));

        crearCarrera.setBackground(new java.awt.Color(0, 153, 0));
        crearCarrera.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        crearCarrera.setText("Crear Carrera");
        crearCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCarreraActionPerformed(evt);
            }
        });
        getContentPane().add(crearCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 140, 80));

        lblGrado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblGrado.setText("Grado:");
        getContentPane().add(lblGrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, -1, -1));

        grados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Licenciatura", "Tecnicatura", "Doctorado", "PostGrado" }));
        getContentPane().add(grados, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, -1, -1));

        lblDescripcionPlan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(lblDescripcionPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 660, 30));

        lblIngresePorcentaje.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIngresePorcentaje.setText("Ingrese el procentaje de Materias Optativas Requeridas para Graduarse (de 30 a 70):");
        getContentPane().add(lblIngresePorcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 520, 30));
        getContentPane().add(jTxtPorcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 60, 30));

        lblIcono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIcono.setText("%");
        getContentPane().add(lblIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, 30, 30));

        Fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getAccessibleContext().setAccessibleName("NuevaCarrera");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        NuevaCarreraController.cerrarVentana();
        MostrarCarrerasController.mostrarVentana();
    }//GEN-LAST:event_backActionPerformed

    private void crearCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCarreraActionPerformed
        // TODO add your handling code here:
        NuevaCarreraController.crearCarrera();
        NuevaCarreraController.cerrarVentana();
        MostrarCarrerasController.mostrarVentana();
    }//GEN-LAST:event_crearCarreraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NuevaCarrera nuevaC = new NuevaCarrera();
                nuevaC.setLocationRelativeTo(null);
                nuevaC.setVisible(true);
            }
        });
    }
    
    public void myInitComponent(){
        ImageIcon image = new ImageIcon("C:\\Users\\eljos\\Documents\\NetBeansProjects\\Facultad\\src\\main\\java\\imagenes\\carreras-universitarias-programas.png");
        Fondo.setIcon(image);
//        NuevaCarreraController.iniciarDescripcion();
    }
    
    public void centrar(){
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    public JLabel getDescripcionPlan() {
        return lblDescripcionPlan;
    }
    
    public String getGradoCarrera(){
        return grados.getSelectedItem().toString();
    }

    public String getListaTiposPlanes() {
        return listaTiposPlanes.getSelectedItem().toString();
    }

    public JTextField getTextCodigoCarrera() {
        return textCodigoCarrera;
    }

    public JTextField getTextNombreCarrera() {
        return textNombreCarrera;
    }

    public void setDescripcionPlan(JLabel descripcionPlan) {
        this.lblDescripcionPlan = descripcionPlan;
    }

    public void setTextCodigoCarrera(JTextField textCodigoCarrera) {
        this.textCodigoCarrera = textCodigoCarrera;
    }

    public void setTextNombreCarrera(JTextField textNombreCarrera) {
        this.textNombreCarrera = textNombreCarrera;
    }

    public JTextField getjTxtPorcentaje() {
        return jTxtPorcentaje;
    }

    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton back;
    private javax.swing.JLabel codigoCarrera;
    private javax.swing.JButton crearCarrera;
    private javax.swing.JComboBox<String> grados;
    private javax.swing.JTextField jTxtPorcentaje;
    private javax.swing.JLabel lblDescripcionPlan;
    private javax.swing.JLabel lblGrado;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblIngresePorcentaje;
    private javax.swing.JComboBox<String> listaTiposPlanes;
    private javax.swing.JLabel nombreCarrera;
    private javax.swing.JTextField textCodigoCarrera;
    private javax.swing.JTextField textNombreCarrera;
    private javax.swing.JLabel tipoPlan;
    // End of variables declaration//GEN-END:variables
}
