/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import controller.MostrarMateriasController;
import controller.NuevaMateriaController;
import javax.swing.*;

/**
 *
 * @author eljos
 */
public class NuevaMateria extends JFrame {

    /**
     * Creates new form NuevaMateria
     */
    public NuevaMateria() {
        initComponents();
        myInitComponent();
        centrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        codigoMateria = new javax.swing.JLabel();
        textCodMateria = new javax.swing.JTextField();
        nombreMateria = new javax.swing.JLabel();
        textNombreMateria = new javax.swing.JTextField();
        determinarTipo = new javax.swing.JLabel();
        tipo = new javax.swing.JComboBox<>();
        año = new javax.swing.JLabel();
        años = new javax.swing.JComboBox<>();
        cuatrismestre = new javax.swing.JLabel();
        cuatrimestres = new javax.swing.JComboBox<>();
        crearMateria = new javax.swing.JButton();
        back = new javax.swing.JButton();
        codigoVerificado = new javax.swing.JLabel();
        nombreVerificado = new javax.swing.JLabel();
        lblPromocion = new javax.swing.JLabel();
        Promocion = new javax.swing.JComboBox<>();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nueva Materia");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        codigoMateria.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        codigoMateria.setText("Código de la Materia");
        getContentPane().add(codigoMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 35, -1, -1));

        textCodMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCodMateriaActionPerformed(evt);
            }
        });
        getContentPane().add(textCodMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 76, 100, -1));

        nombreMateria.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        nombreMateria.setText("Nombre de la Materia");
        getContentPane().add(nombreMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));
        getContentPane().add(textNombreMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 189, 400, -1));

        determinarTipo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        determinarTipo.setText("Determinar el tipo de la Materia");
        getContentPane().add(determinarTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Obligatoria", "Optativa" }));
        tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoActionPerformed(evt);
            }
        });
        getContentPane().add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, -1));

        año.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        año.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        año.setText("año: ");
        getContentPane().add(año, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, 20));

        años.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        getContentPane().add(años, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        cuatrismestre.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        cuatrismestre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuatrismestre.setText("Cuatrimestre:");
        getContentPane().add(cuatrismestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, -1, 20));

        cuatrimestres.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));
        getContentPane().add(cuatrimestres, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, -1, -1));

        crearMateria.setBackground(new java.awt.Color(0, 204, 0));
        crearMateria.setText("Crear Materia");
        crearMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearMateriaActionPerformed(evt);
            }
        });
        getContentPane().add(crearMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 463, 145, 51));

        back.setBackground(new java.awt.Color(255, 0, 0));
        back.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        back.setText("ATRÁS <--");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 35, 145, 53));
        getContentPane().add(codigoVerificado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 80, 10));
        getContentPane().add(nombreVerificado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 120, 20));

        lblPromocion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPromocion.setText("Promocion:");
        getContentPane().add(lblPromocion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, -1, -1));

        Promocion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));
        getContentPane().add(Promocion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, -1, -1));
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoActionPerformed

    private void crearMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearMateriaActionPerformed
        // TODO add your handling code here:
        NuevaMateriaController.crearMateria();
        NuevaMateriaController.cerrarVentana();
        MostrarMateriasController.crearVentana(NuevaMateriaController.idCarrera);
    }//GEN-LAST:event_crearMateriaActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        NuevaMateriaController.back();
    }//GEN-LAST:event_backActionPerformed

    private void textCodMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCodMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCodMateriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NuevaMateria nuevaMateria = new NuevaMateria();
                nuevaMateria.setLocationRelativeTo(null);
                nuevaMateria.setVisible(true);
            }
        });
    }
    
        public void myInitComponent(){
        ImageIcon image = new ImageIcon("C:\\Users\\eljos\\Documents\\NetBeansProjects\\Facultad\\src\\main\\java\\imagenes\\carreras-universitarias-programas.png");
        Fondo.setIcon(image);
    }

    public void centrar(){
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    public void setCodigoVerificado(JLabel codigoVerificado) {
        this.codigoVerificado = codigoVerificado;
    }

    public void setNombreVerificado(JLabel nombreVerificado) {
        this.nombreVerificado = nombreVerificado;
    }

    public String getPromocion() {
        return Promocion.getSelectedItem().toString();
    }

    public String getAños() {
        return años.getSelectedItem().toString();
    }

    public String getCuatrimestres() {
        return cuatrimestres.getSelectedItem().toString();
    }

    public String getTipo() {
        
        return tipo.getSelectedItem().toString();
    }

    
    
    
    
    public JLabel getCodigoVerificado() {
        return codigoVerificado;
    }

    

    public JLabel getNombreVerificado() {
        return nombreVerificado;
    }

   

    public JTextField getTextCodMateria() {
        return textCodMateria;
    }

    public JTextField getTextNombreMateria() {
        return textNombreMateria;
    }

    public void setTextCodMateria(JTextField textCodMateria) {
        this.textCodMateria = textCodMateria;
    }

    public void setTextNombreMateria(JTextField textNombreMateria) {
        this.textNombreMateria = textNombreMateria;
    }
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JComboBox<String> Promocion;
    private javax.swing.JLabel año;
    private javax.swing.JComboBox<String> años;
    private javax.swing.JButton back;
    private javax.swing.JLabel codigoMateria;
    private javax.swing.JLabel codigoVerificado;
    private javax.swing.JButton crearMateria;
    private javax.swing.JComboBox<String> cuatrimestres;
    private javax.swing.JLabel cuatrismestre;
    private javax.swing.JLabel determinarTipo;
    private javax.swing.JLabel lblPromocion;
    private javax.swing.JLabel nombreMateria;
    private javax.swing.JLabel nombreVerificado;
    private javax.swing.JTextField textCodMateria;
    private javax.swing.JTextField textNombreMateria;
    private javax.swing.JComboBox<String> tipo;
    // End of variables declaration//GEN-END:variables
}
