/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import controller.VerHistorialAcademicoController;
import javax.swing.ImageIcon;
import javax.swing.JTable;

/**
 *
 * @author eljos
 */
public class VerHistorialAcademico extends javax.swing.JFrame {

    /**
     * Creates new form VerHistorialAcademico
     */
    public VerHistorialAcademico() {
        initComponents();
        myInitComponent();
        centrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMateriasEnCurso = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableMateriasRegularizadas = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableMateriasAprobadas = new javax.swing.JTable();
        btnRendirFinal = new javax.swing.JButton();
        btnVerificarGraduacion = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lblHistorialAcademico = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Historial Academico");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableMateriasEnCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane1.setViewportView(jTableMateriasEnCurso);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 190, 360));

        jTableMateriasRegularizadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane2.setViewportView(jTableMateriasRegularizadas);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 260, 360));

        jTableMateriasAprobadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane3.setViewportView(jTableMateriasAprobadas);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 220, 360));

        btnRendirFinal.setText("Rendir Final");
        btnRendirFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRendirFinalActionPerformed(evt);
            }
        });
        getContentPane().add(btnRendirFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 190, 50));

        btnVerificarGraduacion.setText("Verificar Graduación");
        btnVerificarGraduacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarGraduacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerificarGraduacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, 190, 50));

        btnBack.setText("VOLVER<--");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, -1, -1));

        jButton1.setText("Ver Examenes Rendidos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 463, 170, 50));

        lblHistorialAcademico.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblHistorialAcademico.setText("Historial Academico:");
        getContentPane().add(lblHistorialAcademico, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        VerHistorialAcademicoController.back();
    }//GEN-LAST:event_btnBackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        VerHistorialAcademicoController.verExamenesRendidos();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnVerificarGraduacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarGraduacionActionPerformed
        // TODO add your handling code here:
        VerHistorialAcademicoController.verificarGraduacion();
    }//GEN-LAST:event_btnVerificarGraduacionActionPerformed

    private void btnRendirFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRendirFinalActionPerformed
        // TODO add your handling code here:
        VerHistorialAcademicoController.rendirFinal();
    }//GEN-LAST:event_btnRendirFinalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerHistorialAcademico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerHistorialAcademico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerHistorialAcademico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerHistorialAcademico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerHistorialAcademico().setVisible(true);
            }
        });
    }

    
    public void myInitComponent(){
        ImageIcon image = new ImageIcon("C:\\Users\\eljos\\Documents\\NetBeansProjects\\Facultad\\src\\main\\java\\imagenes\\carreras-universitarias-programas.png");
        Fondo.setIcon(image);
    }

    public void centrar(){
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }
    
    
    public JTable getjTableMateriasAprobadas() {
        return jTableMateriasAprobadas;
    }

    public JTable getjTableMateriasEnCurso() {
        return jTableMateriasEnCurso;
    }

    public JTable getjTableMateriasRegularizadas() {
        return jTableMateriasRegularizadas;
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRendirFinal;
    private javax.swing.JButton btnVerificarGraduacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableMateriasAprobadas;
    private javax.swing.JTable jTableMateriasEnCurso;
    private javax.swing.JTable jTableMateriasRegularizadas;
    private javax.swing.JLabel lblHistorialAcademico;
    // End of variables declaration//GEN-END:variables
}
